"""add agent_config approval budget audit template skill mcp_server category models

Revision ID: 28b04c37cb48
Revises: 001
Create Date: 2026-04-19 02:32:11.353552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b04c37cb48'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_body', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('response_body', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_path', 'audit_logs', ['path'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('transport', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('config_template', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_mcp_servers_category', 'mcp_servers', ['category'], unique=False)
    op.create_index('ix_mcp_servers_transport', 'mcp_servers', ['transport'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('package_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('litellm_params', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('prompt_template', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('tools', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('skills', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('mcp_servers', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('knowledge', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('memory', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('appearance', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('safety', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('runtime', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('metadata_', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_configs_author_id', 'agent_configs', ['author_id'], unique=False)
    op.create_index('ix_agent_configs_org_id', 'agent_configs', ['org_id'], unique=False)
    op.create_index('ix_agent_configs_visibility', 'agent_configs', ['visibility'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('review_comment', sa.String(length=1000), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_applicant_id', 'approvals', ['applicant_id'], unique=False)
    op.create_index('ix_approvals_org_id', 'approvals', ['org_id'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_rules', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_budgets_org_id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_category', 'templates', ['category'], unique=False)
    op.create_index('ix_templates_org_id', 'templates', ['org_id'], unique=False)
    op.create_index('ix_templates_visibility', 'templates', ['visibility'], unique=False)
    op.create_table('agent_config_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_config_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_config_versions_agent_config_id', 'agent_config_versions', ['agent_config_id'], unique=False)
    op.alter_column('agent_instances', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'openharness'::character varying"))
    op.alter_column('agent_instances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('agent_instances', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agent_instances', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('agent_instances', 'host_node',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('agent_instances', 'workspace_root',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agent_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('api_keys', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_rules', 'price_per_input_token',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('billing_rules', 'price_per_output_token',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('billing_rules', 'effective_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_billing_rules_org_model'), 'billing_rules', type_='unique')
    op.create_unique_constraint('uq_billing_rules_org_id_model', 'billing_rules', ['org_id', 'model'])
    op.alter_column('memory_assets', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'application/octet-stream'::character varying"))
    op.alter_column('memory_assets', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('memory_assets', 'storage_ref',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('memory_assets', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('memory_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memory_assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_memory_assets_org_path'), 'memory_assets', type_='unique')
    op.create_unique_constraint('uq_memory_assets_org_id_path', 'memory_assets', ['org_id', 'path'])
    op.alter_column('organizations', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('task_records', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('task_records', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('task_records', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('task_records', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('task_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usage_records', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('usage_records', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('usage_records', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('usage_records', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usage_records', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('usage_records', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('task_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_records', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('task_records', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('task_records', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('task_records', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('task_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organizations', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint('uq_memory_assets_org_id_path', 'memory_assets', type_='unique')
    op.create_unique_constraint(op.f('uq_memory_assets_org_path'), 'memory_assets', ['org_id', 'path'], postgresql_nulls_not_distinct=False)
    op.alter_column('memory_assets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memory_assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memory_assets', 'metadata_',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('memory_assets', 'storage_ref',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('memory_assets', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('memory_assets', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'application/octet-stream'::character varying"))
    op.drop_constraint('uq_billing_rules_org_id_model', 'billing_rules', type_='unique')
    op.create_unique_constraint(op.f('uq_billing_rules_org_model'), 'billing_rules', ['org_id', 'model'], postgresql_nulls_not_distinct=False)
    op.alter_column('billing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_rules', 'effective_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_rules', 'price_per_output_token',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('billing_rules', 'price_per_input_token',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('agent_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_instances', 'workspace_root',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agent_instances', 'host_node',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('agent_instances', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('agent_instances', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('agent_instances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('agent_instances', 'agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'openharness'::character varying"))
    op.drop_index('ix_agent_config_versions_agent_config_id', table_name='agent_config_versions')
    op.drop_table('agent_config_versions')
    op.drop_index('ix_templates_visibility', table_name='templates')
    op.drop_index('ix_templates_org_id', table_name='templates')
    op.drop_index('ix_templates_category', table_name='templates')
    op.drop_table('templates')
    op.drop_table('budgets')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index('ix_approvals_org_id', table_name='approvals')
    op.drop_index('ix_approvals_applicant_id', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_agent_configs_visibility', table_name='agent_configs')
    op.drop_index('ix_agent_configs_org_id', table_name='agent_configs')
    op.drop_index('ix_agent_configs_author_id', table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_table('skills')
    op.drop_index('ix_mcp_servers_transport', table_name='mcp_servers')
    op.drop_index('ix_mcp_servers_category', table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_table('categories')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_path', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
